- name: unset curl proxy
  lineinfile:
    dest: ~/.curlrc
    regexp: '^proxy='
    state: absent

- name: set curl proxy
  lineinfile:
    dest: ~/.curlrc
    create: yes
    insertafter: EOF
    line: "proxy=http://{{ proxy_host }}:{{ proxy_port }}/"
  when: is_set_proxy
  
