##############################################################
# for packager
##############################################################
- include: ./_packager_yum.yml
  when: ansible_os_family == "RedHat"

- include: ./_packager_dnf.yml
  when:
   - ansible_os_family == "RedHat"
   - ansible_distribution == "Fedora" or ansible_distribution_major_version >= 8


- include: ./_packager_apt.yml
  when:
   - ansible_os_family == "Debian"

##############################################################
# Install tools
##############################################################
- include: ./_change_sources_ubuntu.yml
  when: 
   - ansible_os_family == "Debian"
   - ansible_distribution == "Ubuntu"

- include: ./_install_debian.yml
  when: 
   - ansible_os_family == "Debian"

- include: ./_install_redhat.yml
  when: 
   - ansible_os_family == "RedHat"

##############################################################
# for environment
##############################################################
- include: ./_env_debian.yml
  when: ansible_os_family == "Debian"

- include: ./_env_redhat.yml
  when: ansible_os_family == "RedHat"

##############################################################
# for git
##############################################################
- include: ./_git.yml

##############################################################
# for gem
##############################################################
- include: ./_gem.yml

##############################################################
# for wget
##############################################################
- include: ./_wget.yml

##############################################################
# for curl
##############################################################
- include: ./_curl.yml

##############################################################
# for subversion
##############################################################
- include: ./_subversion.yml

